// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWxBc4iEnpcD5jRiiFszIb9UEdLNqdOi4',
    appId: '1:518180657108:web:b4c845101e04b24beae841',
    messagingSenderId: '518180657108',
    projectId: 'my-app-e9b36',
    authDomain: 'my-app-e9b36.firebaseapp.com',
    storageBucket: 'my-app-e9b36.firebasestorage.app',
    measurementId: 'G-R5Z0L8TZZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2eDiuyo9ikcg2GSoGxQt1C2W4zvV8SjE',
    appId: '1:518180657108:android:786c487db4dd3ebceae841',
    messagingSenderId: '518180657108',
    projectId: 'my-app-e9b36',
    storageBucket: 'my-app-e9b36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHZqDgiknzyIiSO65dPUHynXoBcjQTU0I',
    appId: '1:518180657108:ios:f6ac932ad92355aceae841',
    messagingSenderId: '518180657108',
    projectId: 'my-app-e9b36',
    storageBucket: 'my-app-e9b36.firebasestorage.app',
    iosBundleId: 'com.example.fcmPushApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHZqDgiknzyIiSO65dPUHynXoBcjQTU0I',
    appId: '1:518180657108:ios:f6ac932ad92355aceae841',
    messagingSenderId: '518180657108',
    projectId: 'my-app-e9b36',
    storageBucket: 'my-app-e9b36.firebasestorage.app',
    iosBundleId: 'com.example.fcmPushApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWxBc4iEnpcD5jRiiFszIb9UEdLNqdOi4',
    appId: '1:518180657108:web:180baaf0879e2b41eae841',
    messagingSenderId: '518180657108',
    projectId: 'my-app-e9b36',
    authDomain: 'my-app-e9b36.firebaseapp.com',
    storageBucket: 'my-app-e9b36.firebasestorage.app',
    measurementId: 'G-WBNNV3L5ZB',
  );

}